cluster:
  domain: apps.silver.devops.gov.bc.ca
  ssoAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
  ssoRealm: bcparks-service-transformation
  ssoClientId: staff-portal

images:
  strapiUpgrade:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/strapi-upgrade
    tag: latest


cmsUpgrade:
  componentName: cms-upgrade

  imagePullPolicy: Always

  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  env:
    nodeEnv: production
    databaseMinConnections: 0
    databaseMaxConnections: 10
    databaseIdleTimeout: 30000
    databaseCreateTimeout: 30000
    databaseAcquireTimeout: 30000
    smtpHost: apps.smtp.gov.bc.ca
    smtpPort: 25
    smtpFrom: noreply@gov.bc.ca
    smtpReplyTo: noreply@gov.bc.ca
    cacheEnabled: true
    cacheType: redis
    cacheModels: public-advisory,protected-area
    cacheTtl: 300000
    cacheTimeout: 10000

  service:
    portName: strapi
    port: 1337

  hpa:
    minReplicas: 1
    maxReplicas: 1

patroni:
  componentName: patroni

pgbouncer:
  enabled: true

  componentName: pgbouncer

  service:
    port: 6432

redis:
  componentName: redis

  service:
    port: 6379