name: Deploy to Test

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Tag of version to be promoted to TEST"
        required: true

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools
  ENVIRONMENT: test
  NAMESPACE: ${{ secrets.OPENSHIFT_LICENSE_PLATE }}-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to checkout tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.releaseTag }}

      - name: Tag not found
        if: ${{ failure() }}
        run: |
          echo "::error::Git Tag not found, please double check input"
          exit 1

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_TOKEN }}

      - name: Tag Test images
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag admin:${{ github.event.inputs.releaseTag }} admin:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag public-builder:${{ github.event.inputs.releaseTag }} public-builder:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag strapi:${{ github.event.inputs.releaseTag }} strapi:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag landing:${{ github.event.inputs.releaseTag }} landing:${{ env.ENVIRONMENT }}

      - name: Trigger Gatsby static build workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-public
          client-payload: '{"env": "${{ env.ENVIRONMENT }}", "branch": "main"}'

      - name: Trigger new rollout
        run: |
          oc -n ${{ env.NAMESPACE }} rollout restart deployment bcparks-admin
          oc -n ${{ env.NAMESPACE }} rollout restart deployment bcparks-cms
          oc -n ${{ env.NAMESPACE }} rollout restart deployment bcparks-landing
